Advertising/Controllers/HomeController.cs
using Advertising.Interfaces;
using Advertising.Models;
using Advertising.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;

namespace Advertising.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;
		private ICategoryViewModelService _categoryService;
		private IApplicationService _appService;

		public HomeController(ILogger<HomeController> logger, ICategoryViewModelService categoryService, IApplicationService appService)
		{
			_logger = logger;
			_categoryService = categoryService;
			_appService = appService;
		}

		public async Task<IActionResult> Index(int? id)
		{
			CategoryIndexViewModel categoryModel;
			
			categoryModel = await _categoryService.GetCategories(id); 

			return View(categoryModel);
		}

		public async Task<IActionResult> Edit(int id)
		{
			CategoryViewModel categoryModel = await _categoryService.GetCategory(id);

			return View(categoryModel);
		}

		//public async Task<IActionResult> Edit(CategoryViewModel entity)
		//{
		//	return View();
		//}

		public ActionResult Create()
		{
			return View();
		}

		public ActionResult Delete(int categoryId)
		{
			_categoryService.DeleteCategory(categoryId);
			return View("Index", _categoryService.GetCategories(null).Result);
		}

		// POST: Category/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(CategoryViewModel category)
		{
			try
			{
				_categoryService.AddCategory(category);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Advertising/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Advertising.Core.Entities;
using Advertising.Interfaces;
using Advertising.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace Advertising.Controllers
{
	public class PropertyController : Controller
	{

		private readonly ILogger<PropertyController> _logger;
		private ICategoryViewModelService _categoryService;

		public PropertyController(ILogger<PropertyController> logger, ICategoryViewModelService categoryService, IApplicationService appService)
		{
			_logger = logger;
			_categoryService = categoryService;
		}

		// GET: Property
		public async Task<ActionResult> Index(int? categoryId)
		{
			var properties = await _categoryService.GetProperties(categoryId);
		 	return View(properties);
		}

		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: Property/Create
		public async Task<ActionResult> Create()
		{
			IEnumerable<DataType> v = await _categoryService.GetDataTypes();

			IEnumerable<SelectListItem> items = v.Select(c => new SelectListItem
			{
				Value = c.ID.ToString(),
				Text = c.Name
			});

			ViewBag.DataType = v;
			return View();
		}

		// POST: Property/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(CategoryPropertyViewModel property)
		{
			try
			{

				_categoryService.AddCategoryProperty(property);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: Property/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: Property/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				// TODO: Add update logic here

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: Property/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: Property/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				// TODO: Add delete logic here

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

Advertising/Views/Home/Create.cshtml
@model Advertising.ViewModels.CategoryViewModel

<h4>CategoryViewModel</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*<label asp-for="Id" class="control-label"></label>*@
                <input type="hidden" asp-for="ParrentCategoryId" value="@Model.Id" class="form-control" />
                <span asp-validation-for="ParrentCategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Subcategory name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="New subcategory" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@*<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParrentCategoryId" class="control-label"></label>
                <input asp-for="ParrentCategoryId" class="form-control" />
                <span asp-validation-for="ParrentCategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>*@

<div>
    <a asp-action="Index">Back to List</a>
</div>


Advertising/Views/Home/Edit.cshtml
@model Advertising.ViewModels.CategoryViewModel

<h4>CategoryViewModel</h4>
<hr />


<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			@*<div class="form-group">
					<label asp-for="Id" class="control-label"></label>
					<input type="hidden" asp-for="Id" class="form-control" />
					<span asp-validation-for="Id" class="text-danger"></span>
				</div>*@
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				@*<label asp-for="Id" class="control-label"></label>*@
				<input type="hidden" asp-for="ParrentCategoryId" value="@Model.Id" class="form-control" />
				<span asp-validation-for="ParrentCategoryId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Name" class="control-label">Subcategory name</label>
				<input value="" asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="New subcategory" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>
@Html.ActionLink("Properties", "Index", "Property", new { categoryId = Model.Id })


Subcategories

@if (Model.SubCategoriesList.Any())
{
	@foreach (var cat in Model.SubCategoriesList)
	{
		<div class="esh-catalog-item col-md-4">
			<tr>
				<td>
					@Html.Label(cat.Name + cat.Id)
					@Html.ActionLink("Delete", "Delete", "Home", new { categoryId = cat.Id })
					@Html.ActionLink("Edit", "Edit", "Home", new { id = cat.Id })
				</td>
			</tr>
		</div>
	}
}
<div>
	<a asp-action="Index">Back to List</a>
</div>


Advertising/Views/Home/Index.cshtml
@using Advertising.ViewModels

@model CategoryIndexViewModel

@{
	ViewData["Title"] = "";
}

<div class="text-center">

	@if (Context.User.IsInRole("Admin"))
		@Html.ActionLink("Create new", "Create")


	<form>
		<div class="input-group">
			<input name="ch" class="form-control" type="text" placeholder="Search" />
			<div class="input-group-append">
				<span class="input-group-text" id="basic">
					<i aria-hidden="true"></i>
				</span>
			</div>
		</div>

	</form>

	@if (Model.Categories.Any())
	{
		@foreach (var item in Model.Categories)
		{


			<div class="esh-catalog-item col-md-4">
				<partial name="_category" for="@item" />
			</div>
		}

	}
	else
	{
		<div>
			THERE ARE NO RESULTS THAT MATCH YOUR SEARCH
		</div>
	}
</div>
